### PR TITLE
Update php version constraint

### PR DESCRIPTION
**Pull request by vinkla**
We don't know if it will break in future versions. This way we can be more specifik.

### CODE REVIEW

**Comment by duncan3dc** [comment]
While this makes sense on the face of it, I'm not sure about merging it. PHP itself doesn't really follow semver in the way userland libraries do. They do allow some BC breaks in minor releases, and the breaks they make in majors are often very small and concern very old style code, edge cases, or long deprecated features.

Locking a library to version 1.x makes sense to me as composer can just install 1.x and happily ignore 2.x. But applying that to the php version will cause composer to just reject it, if a user only has php 8.x in the future, and we've added this constraint, composer just doesn't let them doing anything, there's no graceful fallback.

**Comment by vinkla** [comment]
> PHP itself doesn't really follow semver in the way userland libraries do.

This is correct. Though, right now we allow all future version of PHP. We can't control if there will be any breaking changes in `8.0`. This PR doesn't go all the way but takes a step closer to take control of breaking changes in future PHP version.

> But applying that to the php version will cause composer to just reject it, if a user only has php 8.x in the future, and we've added this constraint, composer just doesn't let them doing anything, there's no graceful fallback.

We wont know if this version of the package will be compatible with `8.0`. Composer will install it guessing it should work since we allow it with the current constraint.

**Comment by duncan3dc** [comment]
Do I understand you correct? Would you rather __prevent__ users from installing this on PHP 8? Than let them try it and encounter a bug?

I think it's very unlikely that a change in PHP 8 would affect this library so severely that we should prevent users from installing it at all. The library can't really do anything destructive, a bug would mean maybe the wrong song gets played, I'm not sure we need to go to the extreme to protect users from that, do we?

**Comment by vinkla** [comment]
> Would you rather prevent users from installing this on PHP 8?

Yes I would. In my point of view this means taking responsibility. If users want to run untested versions of PHP with my packages they can still do that with composer by setting custom config.

Since our points of view differ I'll close this pull request. Thanks for getting back and keep up the good work with the package.

**Comment by duncan3dc** [comment]
I've thought about this some more and I was wrong to say composer would just reject it. When someone does `composer require duncan3dc/sonos` it should pull in the version that works with their current php version. However it feels odd to have this pull in some arbitrary version from the 1.x series, so I'll make this change in the [2.x](https://github.com/duncan3dc/sonos/blob/7e60927489d6ea389e6cfe242377d6464972286f/composer.json#L34) version, then there's a clean break. Thanks for your help

**Pull request closed without merging**
